# Generated by Django 4.1.3 on 2022-11-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='created_at',
        ),
    ]
