# Generated by Django 4.1.3 on 2022-11-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0002_remove_personal_info_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='DOM',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Personal_Info/images/'),
        ),
    ]
