# Generated by Django 4.1.3 on 2022-11-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0003_alter_personal_info_dob_alter_personal_info_dom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
