# Generated by Django 4.1.3 on 2022-11-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0006_personal_info_photo_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='Photo_link',
        ),
        migrations.AddField(
            model_name='personal_info',
            name='area',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='organization',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='pin_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='year_of_membership',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
