# Generated by Django 4.1.3 on 2022-11-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0007_remove_personal_info_photo_link_personal_info_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='DOB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='DOM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
