# Generated by Django 4.1.3 on 2022-11-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0008_alter_personal_info_dob_alter_personal_info_dom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
