# Generated by Django 4.1.3 on 2022-11-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0009_alter_personal_info_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Info_App/images/'),
        ),
    ]
