# Generated by Django 4.1.3 on 2022-12-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0011_rename_address_personal_info_proof_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='DOM',
            field=models.DateField(blank=True, null=True),
        ),
    ]
