# Generated by Django 4.1.3 on 2022-12-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0012_alter_personal_info_dob_alter_personal_info_dom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_info',
            old_name='proof_pin_code',
            new_name='holding_COP',
        ),
        migrations.RenameField(
            model_name='personal_info',
            old_name='member_name',
            new_name='member_firstname',
        ),
        migrations.RenameField(
            model_name='personal_info',
            old_name='proof_address',
            new_name='prof_address',
        ),
        migrations.RenameField(
            model_name='personal_info',
            old_name='proof_area',
            new_name='prof_area',
        ),
        migrations.RenameField(
            model_name='personal_info',
            old_name='proof_city',
            new_name='prof_city',
        ),
        migrations.AddField(
            model_name='personal_info',
            name='member_lastname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='prof_pin_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
