# Generated by Django 4.1.6 on 2023-02-06 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0014_form_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_submission',
            name='prof_pin_code',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Invalid postal code')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='residential_pin_code',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Invalid postal code')]),
            preserve_default=False,
        ),
    ]
