# Generated by Django 4.1.6 on 2023-02-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0015_alter_form_submission_prof_pin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_submission',
            name='prof_pin_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='residential_pin_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
