# Generated by Django 4.1.6 on 2023-02-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0017_form_submission_member_middlename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_submission',
            name='corr_prof_address',
        ),
        migrations.RemoveField(
            model_name='form_submission',
            name='corr_prof_area',
        ),
        migrations.RemoveField(
            model_name='form_submission',
            name='corr_prof_city',
        ),
        migrations.RemoveField(
            model_name='form_submission',
            name='corr_prof_pin_code',
        ),
    ]
