# Generated by Django 4.1.6 on 2023-03-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0019_alter_form_submission_membership_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_submission',
            name='holding_COP',
            field=models.CharField(max_length=100),
        ),
    ]
