# Generated by Django 4.1.6 on 2023-03-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0020_alter_form_submission_holding_cop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_submission',
            name='DOB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='DOM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
