# Generated by Django 4.1.6 on 2023-03-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0022_alter_form_submission_member_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_submission',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Info_App/images'),
        ),
    ]
