# Generated by Django 4.1.6 on 2023-03-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0024_alter_form_submission_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_submission',
            name='DOB',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='DOM',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='Phone_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='blood_group',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='email_id',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='member_firstname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='member_lastname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='member_middlename',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='membership_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='organization',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='prof_address',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='prof_area',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='prof_city',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='prof_pin_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='residential_address',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='residential_area',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='residential_city',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='residential_pin_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='year_of_membership',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
