# Generated by Django 4.1.6 on 2023-03-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0026_alter_form_submission_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_submission',
            name='photo',
            field=models.ImageField(upload_to='Info_App/images'),
        ),
    ]
