# Generated by Django 4.1.6 on 2023-03-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0027_alter_form_submission_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_submission',
            name='new_photo',
            field=models.ImageField(default='', upload_to='Info_App/images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
