# Generated by Django 4.1.6 on 2023-03-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0030_alter_form_submission_dob_alter_form_submission_dom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_submission',
            name='new_photo',
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Info_App/images/'),
        ),
    ]
