# Generated by Django 4.1.6 on 2023-03-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0031_remove_form_submission_new_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_submission',
            name='DOB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='DOM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
