# Generated by Django 4.1.6 on 2023-03-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0032_alter_form_submission_dob_alter_form_submission_dom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_submission',
            name='new_photo',
            field=models.ImageField(blank=True, null=True, upload_to='Info_App/images/'),
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='DOB',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='DOM',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
