# Generated by Django 4.1.6 on 2023-03-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0033_form_submission_new_photo_alter_form_submission_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='DOB',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='DOM',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
