# Generated by Django 4.1.6 on 2023-03-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0035_remove_form_submission_new_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_submission',
            name='new_photo',
            field=models.ImageField(blank=True, null=True, upload_to='Info_App/images/'),
        ),
    ]
