# Generated by Django 4.1.6 on 2023-03-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0037_alter_form_submission_dob_alter_form_submission_dom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_submission',
            name='DOB',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='DOM',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
