# Generated by Django 4.1.6 on 2023-03-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0038_alter_form_submission_dob_alter_form_submission_dom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_submission',
            name='holding_COP',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
    ]
