# Generated by Django 4.1.6 on 2023-03-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0039_alter_form_submission_holding_cop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_submission',
            name='holding_COP',
            field=models.CharField(max_length=50),
        ),
    ]
