# Generated by Django 4.1.6 on 2023-03-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0041_alter_form_submission_dob_alter_form_submission_dom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_submission',
            name='member_firstname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='member_lastname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form_submission',
            name='member_middlename',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
