# Generated by Django 4.1.6 on 2023-08-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0043_alter_form_submission_dob_alter_form_submission_dom'),
    ]

    operations = [
        migrations.CreateModel(
            name='mem_photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_number', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='')),
            ],
        ),
    ]
