# Generated by Django 4.1.6 on 2023-05-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0043_alter_personal_info_dob_alter_personal_info_dom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='DOB',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='DOM',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
