# Generated by Django 4.1.6 on 2023-05-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0045_alter_personal_info_dob_alter_personal_info_dom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='DOM',
            field=models.DateField(null=True),
        ),
    ]
