# Generated by Django 4.1.6 on 2023-08-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info_App', '0044_mem_photo'),
        ('Info_App', '0047_alter_personal_info_dom'),
    ]

    operations = [
    ]
